name: 'Sync Action'
description: 'Checks the mergeability of main into nightly and optionally pushes it.'

inputs:
  do_push:
    description: 'Whether to push changes after syncing'
    required: true
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Setting up the repo
      run: |
        git clone https://github.com/amtoine/nu-git-manager /tmp/nu-git-manager
        cd /tmp/nu-git-manager
        git fetch origin main
        git fetch origin nightly:nightly
        git checkout nightly
      shell: bash

    - name: Set up Git
      shell: bash
      run: |
        cd /tmp/nu-git-manager
        git config user.name "$(git log -n 1 --pretty=format:%an)"
        git config user.email "$(git log -n 1 --pretty=format:%ae)"

    - name: Show Git config and worktree
      shell: bash
      run: |
        cd /tmp/nu-git-manager
        git config --list | grep user.name
        git config --list | grep user.email
        git log --graph --branches --remotes --tags --oneline --decorate

    - name: "Attempt to merge main into nightly"
      run: |
        cd /tmp/nu-git-manager
        set +e
        git merge --no-ff origin/main -m "Merge main into nightly"
        MERGE_STATUS=$?
        set -e
        if [ $MERGE_STATUS -ne 0 ]; then
          echo "Merge conflict detected"
          exit 1
        fi
      shell: bash

    - name: "Push to remote"
      run: |
        cd /tmp/nu-git-manager
        git push origin nightly
      shell: bash
      if: ${{ inputs.do_push == 'true' && !env.ACT }}
