name: Sync Action
description: Checks the mergeability of main into nightly and optionally pushes it.

inputs:
  do_push:
    description: Whether to push changes after syncing
    required: true
    default: "false"
  log_worktree:
    description: Whether to log the worktree
    required: true
    default: "false"

permissions:
  contents: write

runs:
  using: composite
  steps:
    - name: Checkout nightly
      run: |
        git fetch origin main
        git fetch origin nightly:nightly
        git checkout nightly
      shell: bash

    - name: Set up Git
      shell: bash
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

    - name: Show Git config and worktree
      shell: bash
      run: |
        git config user.name
        git config user.email
        git log --graph --branches --remotes --tags --oneline --decorate
      if: ${{ inputs.log_worktree == 'true' }}

    - name: "Attempt to merge main into nightly"
      run: |
        set +e
        git merge --no-ff origin/main -m "Merge main into nightly"
        MERGE_STATUS=$?
        set -e
        if [ $MERGE_STATUS -ne 0 ]; then
          echo "Merge conflict detected"
          exit 1
        fi
      shell: bash

    - name: "Push to remote"
      run: git push origin nightly
      shell: bash
      if: ${{ inputs.do_push == 'true' && !env.ACT }}
