---
name: Feature Request
about: Ask for a new feature for `nu-git-manager`
title: ''
labels: ['needs-triage']
assignees: ''
---

<!-- related issues, e.g. "related to #123" -->

## Description
<!-- describe in a few words the feature -->
