name: 🌃 Nightly compatibility check

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  check-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3
      - name: Docker Fix (for act)
        run: |
          git fetch origin
          git reset --hard ${{ github.sha }}
        shell: bash
        if: ${{ env.ACT }}

      - uses: amtoine/merge-branches-action@0.1.0
        with:
          do_push: false
