name: Checking the documentation

on:
  pull_request:
    branches: [main, nightly]
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
      - nightly

jobs:
  check-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository
        uses: actions/checkout@v3

      - uses: hustcer/setup-nu@v3.8
        with:
          version: "0.88.1"

      - name: Check the documentation
        shell: nu {0}
        run: |
          nu --commands $"
            use ($env.PWD)/toolkit.nu
            toolkit doc
            if not \(git status --short | lines | is-empty\) {
              error make --unspanned {
                msg: $'status is non-empty: \(git status --short | lines\)'
              }
            }
          "
