name: 🧪 Tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
  push:
    branches:
      - main
      - nightly

jobs:
  tests:
    uses: ./.github/workflows/nupm-tests.yml
    with:
      nu_version: "0.91.0"
      nupm_revision: "29916fc43aad40ffe901b3c0be8820b9cb78fdba"

  documentation:
    uses: ./.github/workflows/check-documentation.yml
    with:
      nu_version: "0.91.0"
