on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

name: continuous-integration

defaults:
  run:
    shell: bash

env:
  NU_LOG_LEVEL: DEBUG

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-20.04]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v3

      - uses: hustcer/setup-nu@v3.6
        with:
          version: '0.86'

      - name: Install Nupm from Source
        run: git clone https://github.com/nushell/nupm "${{ env.NUPM }}"

      - name: Show Nushell Version
        run: |
          "$HOME/${{ env.NU_BIN }}" --commands "version"

      - name: Run the tests
        run: |
          "$HOME/${{ env.NU_BIN }}" --commands "use ${{ env.NUPM }}/nupm/; nupm test"
