name: 🌃 Sync main to nightly

on:
  pull_request:
    types: [closed]
    branches: [main]

permissions:
  contents: write

jobs:
  sync_on_merge:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          # Fetches all history for all tags and branches
          fetch-depth: 0
      - uses: ./.github/actions/sync_action
        with:
          do_push: true
          log_worktree: true
